### ISSUE TITLE
Google Places occasionally add an extra marker

### ISSUE THREAD

**Issue by bunsushi** [bunsushi/Cinemappr#15]
Google Maps centers on the last added marker. Occasionally, Google Places throws in an extra marker. E.g., I enter a Philly zipcode and the map centers on Franklin, TN. If I navigate to Philly, all theaters in search results have a map marker.

**Comment by lianagitsit** [comment]
Okay, it looks like what’s happening is that it’s making a call to Places using the theater name only - so if there are multiple theaters across the country with the same name, the call returns an array of results and sends whatever the first result is to Maps to render.

There is a Cinemark Movies 10 in Delaware, but there are also ones in seven other states; the first one that returns is in Ohio, so it renders that on the map first. Some logic to restrict the data by zip would probably solve this.

**Comment by lianagitsit** [comment]
Resolved with latest merge.
